In [1]:
import pandas as pd
import numpy as np

# Question 1

## Part (a)

In two sentences, explain the notation $Y_{i}(1)$.

## Part (b)

In two sentences, explain the notation $Y_1(1)$.

## Part (c)

In two sentences, explain the notation $E[Y_i(1)|d_i=0]$.

## Part (d)

In two sentences, explain the difference between the notation $E[Y_i(1)]$ and $E[Y_i(1)|d_i=1]$.

# Question 2: Visual Acuity with Simple Data

In [2]:
table = pd.DataFrame({
    "subject": np.arange(7), 
    "y_0": [10, 12, 15, 11, 10, 17, 16], 
    "y_1": [12, 12, 18, 14, 15, 18, 16], 
    "tau": [2, 0, 3, 3, 5, 1, 0]
    })

In [3]:
table

   subject  y_0  y_1  tau
0        0   10   12    2
1        1   12   12    0
2        2   15   18    3
3        3   11   14    3
4        4   10   15    5
5        5   17   18    1
6        6   16   16    0

## Illustration

Use the values in the table to illustrate that $E[Y_i(1)]-E[Y_i(0)] = E[Y_i(1) - Y_i(0)]$.

To do so, please write code that will index to the correct values in the table and calculate the difference between $E[Y_i(1)]$ and $E[Y_i(0)]$ for each subject. Then, calculate the average of these differences.

In [4]:
# Use this code chunk to show your code work

## Data Possibilities

Is it possible to collect all necessary values and construct a table like the one provided in real life? Explain why or why not?

# Question 3: Visual Acuity

Suppose we are interested in the hypothesis that children playing outside leads them to have better eyesight.

Consider the following population of ten children whose visual acuity we can measure.

-   Visual acuity is the decimal version of the fraction given as output in standard eye exams.
-   Someone with 20/20 vision has acuity 1.0, while someone with 20/40 vision has acuity 0.5.
-   Numbers greater than 1.0 are possible for people with better than “normal” visual acuity.

In [5]:
d = pd.DataFrame({
    "child": np.arange(10), 
    "y_0": [1.2, 0.1, 0.5, 0.8, 1.5, 2.0, 1.3, 0.7, 1.1, 1.4], 
    "y_1": [1.2, 0.7, 0.5, 0.8, 0.6, 2.0, 1.3, 0.7, 1.1, 1.4]
    })

d

   child  y_0  y_1
0      0  1.2  1.2
1      1  0.1  0.7
2      2  0.5  0.5
3      3  0.8  0.8
4      4  1.5  0.6
5      5  2.0  2.0
6      6  1.3  1.3
7      7  0.7  0.7
8      8  1.1  1.1
9      9  1.4  1.4

In this table:

-   `y_1` means the measured *visual acuity* if the child were to play outside at least 10 hours per week from ages 3 to 6\
-   `y_0` means the measured *visual acuity* if the child were to play outside fewer than 10 hours per week from age 3 to age 6;
-   Both of these potential outcomes *at the child level* would be measured at the same time, when the child is 6.

## Treatment effect

Compute the individual treatment effect for each of the ten children.

In [6]:
# Use this code chunk to show your code work

## Story time

Tell a "story" that could explain this distribution of treatment effects. In particular, discuss what might cause some children to have different treatment effects than others.

**Answer:** ...

## True ATE

For this population, what is the true average treatment effect (ATE) of playing outside.

In [7]:
# Use this code chunk to show your code work

## Even-Odd split

Suppose we are able to do an experiment in which we can control the amount of time these children play outside for three years. We happen to randomly assign the odd-numbered children to treatment and the even-numbered children to control. What is the estimate of the ATE you would reach under this assignment? (Please describe your work.)

In [8]:
# Use this code chunk to show your code work

## Biased or Unbiased?

How different is the estimate from the truth? In your own words, why is there a difference? Does this mean that the estimator is a biased or an unbiased estimator? Does this mean that the estimate is biased or unbiased?

In [9]:
# Use this code chunk to show your code/work

## How many splits are possible?

We just considered one way (odd-even) an experiment might split the children. How many different ways (every possible way) are there to split the children into a treatment versus a control group (assuming at least one person is always in the treatment group and at least one person is always in the control group)?

In [10]:
# Use this code chunk to show your code/work

## Observational study

Suppose that we decide it is too hard to control the behavior of the children, so we do an observational study instead. Children 1-5 choose to play an average of more than 10 hours per week from age 3 to age 6, while Children 6-10 play less than 10 hours per week. Compute the difference in means from the resulting observational data.

In [11]:
# Use this code chunk to show your code work

## Observational ATE

Compare your answer in `Observational study` to the true ATE. In your own words what causes the difference? Does this mean that the estimator is a biased or an unbiased estimator? Does this mean that the estimate is biased or unbiased?

In [12]:
# Use this code chunk to show your code work (if needed)